apiVersion: v1
kind: Service
metadata:
  name: {{ include "mvp-sample-front.fullname" . }}
  labels:
{{ include "mvp-sample-front.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.externalIPs }}  
  externalIPs: {{ toYaml .Values.service.externalIPs | nindent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.env.PORT }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mvp-sample-front.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
