apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mvp-sample-bizlogic.fullname" . }}
  labels:
{{ include "mvp-sample-bizlogic.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mvp-sample-bizlogic.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mvp-sample-bizlogic.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME | quote }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}
            - name: DB_ID
              valueFrom:
                secretKeyRef: 
                  name: {{ include "mvp-sample-bizlogic.fullname" . }}
                  key: DB_ID
            - name: DB_PW
              valueFrom:
                secretKeyRef: 
                  name: {{ include "mvp-sample-bizlogic.fullname" . }}
                  key: DB_PW
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: 
                  name: {{ include "mvp-sample-bizlogic.fullname" . }}
                  key: JWT_SECRET
            - name: AUTH_API_URI
              value: {{ .Values.env.AUTH_API_URI | quote }}
            - name: API_PRODUCT_URI
              value: {{ .Values.env.API_PRODUCT_URI | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.env.PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
