apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mvp-sample-bizlogic.fullname" . }}
  labels:
    app: {{ template "mvp-sample-bizlogic.name" . }}
    chart: {{ template "mvp-sample-bizlogic.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  DB_ID: {{ .Values.env.DB_ID | b64enc | quote }}
  DB_PW: {{ .Values.env.DB_PW | b64enc | quote }}
  JWT_SECRET: {{ .Values.env.JWT_SECRET | b64enc | quote }}
