apiVersion: v1
kind: Service
metadata:
  name: {{ include "mvp-sample-bizlogic.fullname" . }}
  labels:
{{ include "mvp-sample-bizlogic.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.env.PORT }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mvp-sample-bizlogic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
