apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-mysql.fullname" . }}
  labels:
{{ include "db-mysql.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalIPs: {{ toYaml .Values.service.externalIPs | nindent 4 }}
  {{- if eq "NodePort" .Values.service.type -}}
  {{- with .Values.service.nodePort }}
  nodePort: {{ . }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: dbport
  selector:
    app.kubernetes.io/name: {{ include "db-mysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
