# Default values for db-mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mysql
  tag: 5.7
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

containerPort:
  name: dbport
  port: 3306

service:
  type: ClusterIP
  port: 3306
  externalIPs:  [ "169.56.164.37", "169.56.164.41" ]

ingress:
  enabled: false

volume:
  server: 169.56.164.243
  path: /nfs/mvp/db-mysql
  capacity: 10Gi
  accessMode: ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain

resources:
  limits:
    cpu: 1024m
    memory: 1024Mi
  requests:
    cpu: 512m
    memory: 512Mi
