apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "login-api.fullname" . }}
  labels:
{{ include "login-api.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "login-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "login-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: wait-db-creation
          image: busybox
          command: ['sh', '-c', 'sleep 5 && until nslookup {{ .Release.Name }}-db-mongodb; do echo waiting for {{ .Release.Name }}-db-mongodb; sleep 5; done;']
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: MONGO_DB_LOGIN_API
              valueFrom:
                secretKeyRef: 
                  name: {{ include "login-api.fullname" . }}
                  key: MONGO_DB_LOGIN_API
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "login-api.fullname" . }}
                  key: JWT_SECRET
            - name: TOKEN_EXPIRE_TIME
              value: {{ .Values.env.TOKEN_EXPIRE_TIME | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
