apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "login-api.name" . }}-test-script
  labels:
    app: {{ template "login-api.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  test.sh: |
    #!/bin/sh
    # Setup script to test MongoDB 
    errorExit () {
      echo; echo "ERROR: $1"; echo; exit 1
    }
    echo "Waiting for mongodb to come up. Host->{{ .Release.Name }}-mongodb"
    until mongo --host {{ .Release.Name }}-mongodb --port {{ .Values.mongodb.service.port }} --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
    echo "Waiting for db availability"
    sleep 2
    done
    echo "DB ready. Checking..."
    mongo --host {{ .Release.Name }}-mongodb --port {{ .Values.mongodb.service.port }} -u {{ .Values.mongodb.db.nodeUser }} -p {{ .Values.mongodb.db.nodePassword }} < /scripts/testMongodb.js || errorExit "Test failed. Can't get db & user"
    echo "DB test done"
  testMongodb.js: |
    // Get custom database & user in the db
    var customDb = db.getSiblingDB("{{ .Values.mongodb.db.name }}");
    customDb.getUser("{{ .Values.mongodb.db.nodeUser }}");

